### PR TITLE
fixing derivative DSIDs

### PR DESCRIPTION
**Pull request by qadan**

### CODE REVIEW

**Comment by daniel-dgi** [comment]
Yeah, it is.  That's my bad for not linking to that ticket in our internal ticket.

**Comment by daniel-dgi** [comment]
Updated internal ticket to link to https://jira.duraspace.org/browse/ISLANDORA-1419.  Yes, it will get reviewed shortly.

**Comment by qadan** [comment]
Sorry; I should have figured there would be a ticket in the Islandora JIRA for this. Side-note: the ingest test for this appears to expect a JPG and a TN datastream; are these added to web archive objects no matter what? otherwise it would be strange to have the tests passing without them

**Comment by qadan** [comment]
Actually, those tests don't appear to be running: https://travis-ci.org/Islandora/islandora_solution_pack_web_archive/jobs/73945229

Perhaps as a part of this fix those tests should be updated, and the .yml should be repaired?

**Comment by qadan** [comment]
Yep, that should definitely happen. Looks like the .test file isn't listed in the .info 'files' array, so the test class would never have gotten registered. I'll fix/update the tests and add them to the pull request.

**Comment by qadan** [comment]
Do we expect empty datastreams for the WARC_FILTERED and WARC_CSV at the end of the test?

**Comment by qadan** [comment]
Fixin' that while I'm in there

**Comment by qadan** [comment]
no prawb bub! the previous travis build is lagging and being horrible, but hopefully the new one should be fine

**Pull request merged**
